name: Add GCP Environment

on:
  workflow_dispatch:
    inputs:
      environment_name:
        description: 'Name of the new GitHub environment'
        required: true
      project_id:
        description: 'GCP Project ID'
        required: true

jobs:
  add-environment:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Create new environment
        run: |
          echo "Creating environment ${{ inputs.environment_name }}..."
          gh api -X POST /repos/SlavkoVen/challengetask/environments -f name="${{ inputs.environment_name }}"

      - name: Set GCP project secrets
        run: |
          echo "Setting GCP Project ID..."
          gh secret set GCP_PROJECT_ID --body "${{ inputs.project_id }}"
          echo "Setting GCP Service Account Key..."
          gh secret set GCP_SERVICE_ACCOUNT_KEY --body "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}"
          echo "Environment and secrets for GCP Project ${{ inputs.project_id }} created successfully."
