name: Add GCP Project Environment

on:
  workflow_dispatch:
    inputs:
      environment_name:
        description: 'Name of the GitHub environment'
        required: true
      gcp_project_id:
        description: 'GCP Project ID'
        required: true
      gcp_service_account_key:
        description: 'GCP Service Account Key'
        required: true

jobs:
  add-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Set GCP Project ID secret
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh secret set GCP_PROJECT_ID --env ${{ github.event.inputs.environment_name }} --body "${{ github.event.inputs.gcp_project_id }}"
      
      - name: Set GCP Service Account Key secret
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh secret set GCP_SERVICE_ACCOUNT_KEY --env ${{ github.event.inputs.environment_name }} --body "${{ github.event.inputs.gcp_service_account_key }}"

      - name: Confirm Secrets Set for Environment
        run: |
          echo "Secrets set for environment: ${{ github.event.inputs.environment_name }}"
