name: Check Environment Secrets

on:
  workflow_dispatch:

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check GCP Project ID Secret
        run: |
          echo "GCP Project ID: ${{ secrets.GCP_PROJECT_ID }}"

      - name: Check GCP Service Account Key Secret
        run: |
          echo "GCP Service Account Key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}"
