name: Create Environment Example
on:
  push:
    branches:
      - main

jobs:
  create-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Create new environment
        run: |
          echo "Creating environment ${{ inputs.environment_name }}..."
          gh api POST /repos/SlavkoVen/challengetask/settings/environments -f name=${{ inputs.environment_name }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
