name: Add GCP Environment

on:
  workflow_dispatch:
    inputs:
      environment_name:
        description: 'Name of the new GitHub environment'
        required: true
      project_id:
        description: 'GCP Project ID'
        required: true

jobs:
  add-environment:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} #  Add GH_TOKEN  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create new environment
        run: |
          gh api -X POST repos/:owner/:repo/environments/${{ inputs.environment_name }} \
            -f environment=${{ inputs.environment_name }}

      - name: Set GCP project secrets
        run: |
          gh secret set GCP_PROJECT_ID --body "${{ inputs.project_id }}"
          gh secret set GCP_SERVICE_ACCOUNT_KEY --body "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}"
          echo "Environment and secrets for GCP Project ${{ inputs.project_id }} created successfully."
