name: Add GCP Environment

on:
  workflow_dispatch:
    inputs:
      environment_name:
        description: 'Name of the new GitHub environment'
        required: true
      project_id:
        description: 'GCP Project ID'
        required: true

jobs:
  add-environment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create new environment
        run: |
          gh api -X POST repos/:owner/:repo/environments/${{ inputs.environment_name }} \
            -f environment=${{ inputs.environment_name }}

      - name: Set GCP project secrets
        run: |
          gh secret set GCP_PROJECT_ID --body "${{ inputs.project_id }}"
          gh secret set GCP_SERVICE_ACCOUNT_KEY --body "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}"
          echo "Environment and secrets for GCP Project ${{ inputs.project_id }} created successfully."
      
      - name: Deploy to Google Cloud Run
        run: |
          echo "Starting deployment to environment ${{ inputs.environment_name }}"
          # Команди для деплойменту, з використанням secret'ів GCP
          gcloud config set project "${{ inputs.project_id }}"
          gcloud run deploy --image gcr.io/${{ inputs.project_id }}/my-image --region us-central1
