name: Add GCP Environment

on:
  workflow_dispatch:
    inputs:
      environment_name:
        description: 'Name of the new GitHub environment'
        required: true
      project_id:
        description: 'GCP Project ID'
        required: true

jobs:
  add-environment:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.PAT_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set GCP project secrets
        run: |
          echo "Setting GCP Project ID..."
          gh secret set GCP_PROJECT_ID --body "${{ inputs.project_id }}"
          echo "Setting GCP Service Account Key..."
          echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" > service_account_key.json
          gh secret set GCP_SERVICE_ACCOUNT_KEY < service_account_key.json
          rm service_account_key.json
          echo "Environment and secrets for GCP Project ${{ inputs.project_id }} created successfully."
