name: Deploy Endpoints to GC Run

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GAR_LOCATION: ${{ secrets.GAR_LOCATION }}
  REPOSITORY: 'my-docker-repo'
  HTTPS_IMAGE: 'https-endpoint'
  FIRESTORE_IMAGE: 'firestore-endpoint'
  SCHEDULER_IMAGE: 'scheduler-endpoint'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Authenticate Docker to Google Cloud Artifact Registry
        run: |
          gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev
               
      - name: Build and Push HTTPS Docker Image
        run: |
          docker build -t ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.HTTPS_IMAGE }}:${{ github.sha }} -f https_trigger/Dockerfile https_trigger
          docker push ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.HTTPS_IMAGE }}:${{ github.sha }}
      
      - name: Build and Push Firestore Docker Image
        run: |
          docker build -t ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.FIRESTORE_IMAGE }}:${{ github.sha }} -f firestore_trigger/Dockerfile firestore_trigger
          docker push ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.FIRESTORE_IMAGE }}:${{ github.sha }}
      
      - name: Build and Push Scheduler Docker Image
        run: |
          docker build -t ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SCHEDULER_IMAGE }}:${{ github.sha }} -f scheduler_trigger/Dockerfile scheduler_trigger
          docker push ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SCHEDULER_IMAGE }}:${{ github.sha }}
      
      - name: Deploy HTTPS Endpoint to Google Cloud Run
        run: |
          gcloud run deploy ${{ env.HTTPS_IMAGE }} --image ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.HTTPS_IMAGE }}:${{ github.sha }} --region ${{ env.GAR_LOCATION }} --platform managed --allow-unauthenticated
      
      - name: Deploy Firestore Endpoint to Google Cloud Run
        run: |
          gcloud run deploy ${{ env.FIRESTORE_IMAGE }} --image ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.FIRESTORE_IMAGE }}:${{ github.sha }} --region ${{ env.GAR_LOCATION }} --platform managed --allow-unauthenticated
      
      - name: Deploy Scheduler Endpoint to Google Cloud Run
        run: |
          gcloud run deploy ${{ env.SCHEDULER_IMAGE }} --image ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SCHEDULER_IMAGE }}:${{ github.sha }} --region ${{ env.GAR_LOCATION }} --platform managed --allow-unauthenticated
