name: Deploy to Google Container Registry (GCR)

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GAR_LOCATION: ${{ secrets.GAR_LOCATION }}
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Authenticate Docker to Google Cloud Artifact Registry
        run: |
          gcloud auth configure-docker us-docker.pkg.dev

      - name: Build Docker Image
        run: |
          docker build -t us-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-app:${{ github.sha }} .

      - name: Push Docker Image to Artifact Registry
        run: |
          docker push us-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-app:${{ github.sha }}

