name: Deploy Endpoints to Google Cloud Run

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GAR_LOCATION: 'us-central1'
  REPOSITORY: 'my-docker-repo'
  HTTPS_IMAGE: 'https-endpoint'
  FIRESTORE_IMAGE: 'firestore-endpoint'
  SCHEDULER_IMAGE: 'scheduler-endpoint'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true

      - name: Authenticate Docker to Google Cloud Artifact Registry
        run: |
          gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev

      - name: Build and Push HTTPS Docker Image
        run: |
          docker build -t ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.HTTPS_IMAGE }}:${{ github.sha }} -f https_trigger/Dockerfile https_trigger
          docker push ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.HTTPS_IMAGE }}:${{ github.sha }}

      - name: Deploy HTTPS Endpoint to Google Cloud Run
        run: |
          gcloud run deploy https-endpoint --image ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.HTTPS_IMAGE }}:${{ github.sha }} --region ${{ env.GAR_LOCATION }} --platform managed --allow-unauthenticated
